NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = 0				-- Prestige transferred for the Request to Share Maps diplomatic action.
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0
NDefines.NDiplomacy.MAX_PEACE_TREATY_COST = 100
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 15
NDefines.NDiplomacy.ANNUL_TREATIES_YEARS = 20
NDefines.NDiplomacy.COALITION_YEARS = 5
NDefines.NDiplomacy.REVANCHISM_MONTHLY_DECAY = 0.833
NDefines.NDiplomacy.MAX_ASKED_TRADE_POWER = 100
NDefines.NDiplomacy.COUNTERESPIONAGE_DISCOVER_CHANCE = 0.50
NDefines.NDiplomacy.SPY_NETWORK_SIEGE_EFFECT = 0.10
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.33
NDefines.NDiplomacy.PEACE_COST_FORCE_MIGRATION = 100.0
NDefines.NDiplomacy.PEACE_COST_DEMAND_NON_OCCUPIED_PROVINCE_MULT = 1
NDefines.NDiplomacy.ANNEX_DIP_COST_PER_DEVELOPMENT = 8
NDefines.NDiplomacy.DEFENDER_AE_MULT = 0.5
NDefines.NDiplomacy.STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 5
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 5
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 5
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 6
NDefines.NDiplomacy.MINIMUM_TRADE_POWER_TO_PREVENT_PRIVATEER = 0.1
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
NDefines.NDiplomacy.MIN_MONTHLY_COST_FOR_INFLUENCE_NATION = 2.084
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 5
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 300
NDefines.NDiplomacy.AUTONOMY_WARSCORE_COST_MODIFIER = 0.5			-- How much autonomy reduces score by (at 1, 50% autonomy = 50% reduction)
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0
NDefines.NDiplomacy.DESIRED_NUM_OF_ELECTORS = 5
NDefines.NDiplomacy.MAX_FREE_CITIES = 13
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 10
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = -0.05
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.FABRICATE_CLAIM_COST_MODIFIER_PER_CLAIM = 0.25
NDefines.NDiplomacy.CLAIM_STATE_MODIFIER = 0.25

NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.6
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 1					-- Demand a province (scales by province wealth, also used for annex)
NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 1
NDefines.NDiplomacy.PEACE_COST_GOLD_STEP = 4
NDefines.NDiplomacy.PEACE_COST_WAR_REPARATIONS = 5
NDefines.NDiplomacy.PEACE_COST_HUMILIATE_RIVAL = 30

NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.01
NDefines.NDiplomacy.FORCE_BREAK_ALLIANCE_TRUCE_YEARS = 0
NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0						-- Tributary State: Part of yearly income given in tribute
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.12						-- Tributary State: Part Adm tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.12						-- Tributary State: Part Dip tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.12						-- Tributary State: Base Mil tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.375					-- Tributary State: Part of yearly manpower given in tribute
NDefines.NDiplomacy.TRIBUTE_SENT_TRUST = 5						-- Tributary State: Bilateral Trust if tribute sent
NDefines.NDiplomacy.TRIBUTE_REFUSED_TRUST = 0
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 6	
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 1
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.48
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.12
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -20.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 1.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.36
NDefines.NCountry.PROSPERITY_INCREASE_SIZE = 2
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 30
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = 0
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.NEW_HEIR_LEGITIMACY_HIT = 0
NDefines.NCountry.NEW_HEIR_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.008		-- per dev
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.002	-- distance
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = 0.25	-- different continet
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.5		-- non accepted culture
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 1			-- Required prestige to to upgrade to government rank 2
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 25
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5
NDefines.NCountry.ESTATE_AGENDA_ABOUT_TO_EXPIRE_WARNING = 365
NDefines.NCountry.PARLIAMENT_BACKING_PERCENTAGE = 40			-- average percent of seats backing an issue (0-100)
NDefines.NCountry.NUM_PARLIAMENT_ISSUES = 10
NDefines.NCountry.PARLIAMENT_PRESTIGE_HIT = 0				-- penalty if failed debate.
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 32
NDefines.NCountry.EXPLORE_COAST_EVENT_CHANCE = 2
NDefines.NCountry.MINIMUM_POLICY_TIME = 1
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 2.5
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 0.125
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = 0
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 7.5
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 5
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 0
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 0
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 5
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 5
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_MAKE_PROVINCE_CORE = 10
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NCountry.PS_MOVE_CAPITAL_EXTRA = 20
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE = 0
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE_CAP = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_SEIZE_COLONY = 5
NDefines.NCountry.PS_ATTACK_NATIVES = 1
NDefines.NCountry.PS_HARSH_TREATMENT_COST = 50
NDefines.NCountry.PS_GARRISON_SORTIES = 25
NDefines.NCountry.PS_IMPROVE_PROVINCE_CAPITAL_DISCOUNT = 0.005
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 0
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 20
NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 30.0
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 25
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.CORE_HAD_PERMANENT_CLAIM = 0.15
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.REGULAR_COLONY_GROWTH = 55
NDefines.NCountry.ANCESTOR_COST = 200
NDefines.NCountry.COLONIAL_CLAIM_BONUS = 20
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = 0
NDefines.NCountry.COLONY_VIOLAION_PAPAL_INFLUENCE_COST  = 0
NDefines.NCountry.MONTHS_TO_CORE = 36
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7.5
NDefines.NCountry.STARTING_FLEET_SIZE = 0.9
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_1_TECH = 28
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_TECH = 30
NDefines.NCountry.LIBERTY_DESIRE_WAR_EXHAUSTION = 0				-- Liberty desire from overlord's war exhaustion (per WE)
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0
NDefines.NCountry.LIBERTY_DESIRE_HISTORICAL_RIVAL = 0
NDefines.NCountry.MAX_CROWN_COLONIES = 4
NDefines.NCountry.NORMAL_ELECTION_CYCLE = 5
NDefines.NCountry.SEIZE_TERRITORY_LIBERTY_MULTIPLIER = 3
NDefines.NCountry.HORDE_UNITY_PER_LOOT = 0.5
NDefines.NCountry.PILLAGE_CAPITAL_MAX_DEV_PILLAGED = 6
NDefines.NCountry.DEBT_LIMIT_MIL = -999
NDefines.NCountry.PROMOTE_INVESTMENTS_TRADEPOWER = 0
NDefines.NCountry.PROMOTE_INVESTMENTS_INFLATION = 0
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0.1
NDefines.NCountry.PILLAGE_CAPITAL_DEVELOPMENT_DECREASE = 0.2
NDefines.NCountry.PILLAGE_CAPITAL_MAX_DEV_PILLAGED = 6
NDefines.NCountry.SCUTAGE_TAX_FRACTION = 0.25
NDefines.NCountry.INNOVATIVENESS_AHEAD_OF_TIME_BONUS = 0.005
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2.0  -- Innovativeness bonus to first country (or countries) to reach a certain tech level.
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1.0			-- Innovativeness bonus to first country (or countries) to pick an idea.
NDefines.NCountry.SETTLEMENT_GROWTH_DEVELOPMENT_INCREASE = 0 -- How much development may increase per year if a colonist is working on Settlement Growth.
NDefines.NCountry.SETTLMENT_GROWTH_CHANCE_MULTIPLIER = 2
NDefines.NCountry.RAZE_PROVINCE_DEVELOPMENT_DECREASE = 0.1
NDefines.NCountry.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 0														
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 7						
NDefines.NCountry.PROMOTE_COST_MONTHS_ADVISOR_SALARY = 100.0		
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.75				-- Multiplier on cost for advisors scripted with discount=yes
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 10 
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 5

NDefines.NEconomy.EDICTS_COST_INCREASE = 1.5
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 3
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 10
NDefines.NEconomy.GOLD_MINE_SIZE = 30
NDefines.NEconomy.TRADE_POWER_HOME_BONUS = 0.25
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30
NDefines.NEconomy.COLONY_MIN_AUTONOMY = 75
NDefines.NEconomy.DECREASE_AUTONOMY_STEP = -5
NDefines.NEconomy.DECREASE_AUTONOMY_MIN = 0
NDefines.NEconomy.INCREASE_AUTONOMY_STEP = 5
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.025
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.1
NDefines.NEconomy.TRADE_WIND_STRENGTH = 0
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = -0.2
NDefines.NEconomy.TRADE_ADDED_VALUE_MODIFER = 0.05
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 25
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 0.1
NDefines.NEconomy.TRADE_COMPANY_COOLDOWN = 6
NDefines.NEconomy.LARGE_COLONIAL_NATION_LIMIT = 15
NDefines.NEconomy.PRIVATEER_INCOME_COLLECTION_EFF = 0.1
NDefines.NEconomy.CARAVAN_FACTOR = 10
NDefines.NEconomy.CARAVAN_POWER_MAX = 20
NDefines.NEconomy.CARAVAN_POWER_MIN = 1
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0

NDefines.NMilitary.WARDEC_COBELLI_FOR_TRADE_LEAGUES = 0
NDefines.NMilitary.SLACKEN_AP_DROP = 0.1
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 33.3
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 90
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = -0.10
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 1
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 1
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 1
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 1					-- Starting strength of a banner regiment, 1.0 being full strength
NDefines.NMilitary.CAWA_STARTING_STRENGTH = 1				-- Starting strength of a cawa regiment, 1.0 being full strength
NDefines.NMilitary.CAWA_STARTING_MORALE = 0.25
NDefines.NMilitary.COSSACKS_MAXIMUM_RATIO = 1					-- Maximum number of Cossacks regiments, relative to force limit
NDefines.NMilitary.REVOLUTIONARY_GUARD_MAXIMUM_RATIO = 0.1			-- Maximum number of Revolutionary Guard regiments, relative to force limit
NDefines.NMilitary.REVANCHISM_DEVASTATION_IMPACT = -0.3
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 1
NDefines.NMilitary.GARRISON_SIZE = 3000 							-- GARRISON_SIZE
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER =  0.334			-- x times garrison to be able to siege.
NDefines.NMilitary.MAX_BREACH = 1
NDefines.NMilitary.TRANSPORT_SHIP_SAILORS_COST = 20					-- 1 = 1 men in cost.
NDefines.NMilitary.LIGHT_SHIP_SAILORS_COST = 50					-- 1 = 1 men in cost.
NDefines.NMilitary.GALLEY_SHIP_SAILORS_COST = 50
NDefines.NMilitary.GALLEY_TIME = 90							-- _MDEF_GALLEY_TIME = 10,
NDefines.NMilitary.TRANSPORT_TIME = 30				-- 1 = 1 men in cost.
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 10
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2							-- _MDEF_LIGHT_SHIP_COST = 10,
NDefines.NMilitary.GALLEY_COST = 10 								-- _MDEF_GALLEY_COST = 10,
NDefines.NMilitary.TRANSPORT_COST = 1
NDefines.NMilitary.FORTRESS_COST = 0.075
NDefines.NMilitary.MERCENARY_BASE_COST = 25.0
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 25
NDefines.NMilitary.MERCENARY_REINFORCE_COST_MULTIPLIER = 0.25
NDefines.NMilitary.MERCENARY_COMPANY_HIRING_COST_MONTHS = 36
NDefines.NMilitary.TRADITION_GAIN_LAND = 25
NDefines.NMilitary.LOOTED_SCALE = 2
NDefines.NMilitary.LOOTED_MAX = 10
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 8.0
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = 0
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.67
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50
NDefines.NMilitary.WAR_ENTHUSIASM_HIGH_THRESHOLD = -15
NDefines.NMilitary.DAYS_PER_PHASE = 2
NDefines.NMilitary.COMBAT_DICE_SIDE = 7
NDefines.NMilitary.REBEL_LEADER_POWER = 10
NDefines.NMilitary.SEA_LANDING_PENALTY = -1
NDefines.NMilitary.PRESTIGE_TO_TRIBAL_ALLEGIANCE_FACTOR = 6
NDefines.NMilitary.FORT_FLIPPING_TIME = 15
NDefines.NMilitary.STACKWIPE_MANPOWER_RETURN_FRACTION = 0.1
NDefines.NMilitary.NAVAL_BASE_ENGAGEMENT_WIDTH = 25
NDefines.NMilitary.LEADER_GAIN_PERSONALITY_BASE_CHANCE = 25.0
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 0
NDefines.NMilitary.RESERVE_TICK_DAMAGE = 0.1
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 5
NDefines.NMilitary.CREATE_CAWA_MIL_COST = 10
NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 1.25				-- Rajput base cost is double as expensive
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 1
NDefines.NMilitary.MAX_DRILL_DECAY = 0.75
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 1
NDefines.NMilitary.JANISSARIES_USES_CONSTRUCTION = 1
NDefines.NMilitary.CAWA_USES_CONSTRUCTION = 1
NDefines.NMilitary.FLAGSHIP_REQUIRED_NAVY_SIZE_IN_SAILORS = 750
NDefines.NMilitary.MERCENARY_COMPANY_STARTING_MORALE = 0.25
NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 8
NDefines.NMilitary.MERCENARY_COMPANY_ARMY_TRADITION = 15.0
NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_PER_REGIMENT = 1.125
NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_RECOVERY = 90				-- How many months to recover mercenary manpower fully
NDefines.NMilitary.MERCENARY_COMPANY_HIRED_MANPOWER_RECOVERY_MOD = 2
NDefines.NMilitary.SIEGE_BONUS_FOOD_SHORTAGE = 1
NDefines.NMilitary.SIEGE_BONUS_WATER_SHORTAGE = 1
NDefines.NMilitary.SIEGE_BONUS_DEFENDERS_DESERT = 1
NDefines.NMilitary.NAVAL_DOCTRINE_SAILORS_COST = 0.05			-- Cost for switching naval doctrine (Share of sailors)
NDefines.NMilitary.NAVAL_DOCTRINE_MIN_FORCE_LIMIT = 15
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0	-- Multiplier for morale damage taken by backrow
NDefines.NMilitary.BACK_LINE_STRENGTH_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.CAVALRY_COST = 30
NDefines.NMilitary.STRELTSY_FIRE_DAMAGE_BONUS = 0.05
NDefines.NMilitary.CAVALRY_BREAKTHROUGH = 0.15

NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 1
NDefines.NAI.ACCEPTABLE_FRACTION_OF_INTEREST_PAYMENTS = 0.4
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.05
NDefines.NAI.MIN_CAV_PERCENTAGE = 0 --AI will always try to have at least this many % of their army as cav, regardless of time in the game.
NDefines.NAI.MAX_CAV_PERCENTAGE = 100
NDefines.NAI.DEVELOP_IN_SUBJECTS_PREFERENCE = 1
NDefines.NAI.AI_BUY_PROVINCE_SUBJECT_MAX_OE = 150 -- % of OE (including OE from sold province) above which AI who is a subject will not buy non-core provinces (Not used if OE is at 0)
NDefines.NAI.SUBSIDY_YEARS = -1 -- Years AI will give subsidies for
NDefines.NAI.MIN_INCOME_FOR_SUBSIDIES = -1 -- Minimum monthly income for AI to want to spend some on subsidies
NDefines.NAI.PS_SHORT_TERM_POOL = 100 -- Max power AI will store in its short-term spending pool
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.5 -- AI will spend a maximum of this fraction of monthly income on advisor maintenance
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 61
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.9
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.33 -- AI will spend a minimum of this fraction of monthly income on advisor maintenance
NDefines.NAI.ADVISOR_BUDGET_THRESHOLD = 1.25 -- The AI will only hire an advisor if it can afford this much maintenance increase (+25%)
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 80.0				-- AI scoring for redruiting advisors, multiplied by budget/cost
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 50.0						-- AI scoring for promoting advisors, multiplied by budget/cost
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 3
NDefines.NAI.AGGRESSIVENESS = 5000 -- Base chance (out of 10000) of AI being willing to start a war each diplomatic tick (~1.5 times a month)
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 1250 -- Added to aggressiveness if the war is against a weak or particularily hated enemy
NDefines.NAI.MISSION_PICK_CHANCE = 100
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 1 -- AI must have at least this many monthly deficits of savings to be willing to deficit spend
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 1 -- Same as DEFICIT_SPENDING_MIN_MONTHS, but during peacetime, no rebels and no war exhaustion
NDefines.NAI.BIGSHIP_FRACTION = 0.1
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 13 -- Tech level at which AI will double its artillery fraction
NDefines.NAI.TRANSPORT_FRACTION = -1 -- Max fraction of naval forcelimit that should be transports
NDefines.NAI.INCOME_SAVINGS_FRACTION = -1 -- AI will reserve this amount of their surplus for long-term savings
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 0.001 -- The higher this number is, the less willing the AI will be to exceed forcelimits
NDefines.NAI.MILITARISE_FORT_BUDGET_FACTOR = 0.1 --if the country should militarise, multiply fort budget priority by this
NDefines.NAI.DESIRED_DEFICIT = 0.125
NDefines.NAI.DESIRED_SURPLUS = 0.125
NDefines.NAI.DESIRED_SURPLUSEXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.05 -- AI will aim for having at least this fraction of their income as additional surplus when they need buildings
NDefines.NAI.MAX_SAVINGS = 150 -- AI will keep a maximum of this * their monthly income in long-term savings
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 50.0

NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.15 -- AI will spend a maximum of this fraction of monthly income on state maintenance
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.3
NDefines.NAI.ARMY_BUDGET_FRACTION = 1.2
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_FRIEND_IN_COMBAT = 0.45
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_OFFENSIVE = 0.55
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.6
NDefines.NAI.FORT_BUDGET_FRACTION = 0.1
NDefines.NAI.REGIMENTS_PER_GENERAL = 24
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 175 -- If border distance is greater than this, diplomatic AI will have less interest in the country
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 135
NDefines.NAI.PURSUE_DISTANCE = 90
NDefines.NAI.BASE_CAN_MAKE_CORE_DESIRE_TO_RETURN_PROVINCE = 15
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 1
NDefines.NAI.DEBASE_THRESHOLD = -1-- AI will not debase if it has more gold than this.
NDefines.NAI.DEVELOPMENT_CAP_BASE = 20	-- AI will not develop provinces that have more development than this or DEVELOPMENT_CAP_MULT*original development (whichever is bigger)
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1

NDefines.NAI.PEACE_TIME_MONTHS = 12
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0
NDefines.NAI.PEACE_WARGOAL_FACTOR = 0.5 -- AI unwillingness to peace based on holding the wargoal
NDefines.NAI.PEACE_CAPITAL_FACTOR = 20
NDefines.NAI.PEACE_ALLY_WARSCORE_MULT = 1
NDefines.NAI.PEACE_ALLY_WARGOAL_MULT = 2 -- Multiplies PEACE_WARGOAL_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_CAPITAL_MULT = 1
NDefines.NAI.PEACE_DESPERATION_FACTOR = 20
NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 50 -- How much AI wants to peace out when player enabled AI setting "Seek Quick Peace"
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 0
NDefines.NAI.PEACE_TERMS_VASSAL_BASE_MULT = 1000.0
NDefines.NAI.PEACE_TERMS_PILLAGE_CAPITAL_MULT = 0.5
NDefines.NAI.PEACE_TERMS_PROVINCE_BASE_MULT = 9.0
NDefines.NAI.PEACE_TERMS_TRADE_POWER_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_HUMILIATE_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_REVOKE_CORES_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_REVOKE_REFORM_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_RETURN_CORES_BASE_MULT =0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_GOLD_BASE_MULT = 0.005
NDefines.NAI.PEACE_TERMS_GIVE_UP_CLAIM_PERMANENT = 0.4
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 0.8 -- AI desire for a province is multiplied by this if it doesn't have a valid cb for it (only used when annexing, not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 25.0 -- AI desire for a province is multiplied by this if it has a core on it
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 15.0 -- AI desire for a province is multiplied by this if it is the wargoal
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 10.0 -- AI desire for a province is multiplied by this if it has a claim on it
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 1 -- AI desire for a province is multiplied by this if it is not the same culture
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 2 -- AI desire for a province is multiplied by this if it would go to their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_PROVINCE_REAL_ADJACENT_MULT = 5 -- AI desire for a province is increased by this multiplier for each owned adjacent province
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.4 -- AI desire for a province is multiplied by this if it is not adjacent at all (including vassals and other provinces being taken in peace)
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0.1
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 2.75 -- AI desire for a province is multiplied by this if it has 0% overextension (not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_ISOLATED_CAPITAL_MULT = 0.75 -- AI desire for a province if it is capital (costs a bit more to take)
NDefines.NAI.PEACE_TERMS_PROVINCE_ALLY_MULT = 0.65
NDefines.NAI.PEACE_TERMS_TRADE_POWER_VALUE_MULT = 0.65 -- AI desire for transfering trade power is multiplied by this for each 0.1 trade value in shared nodes
NDefines.NAI.PEACE_TERMS_TRADE_POWER_VALUE_MAX = 2.75 -- Max AI desire for transfering trade power from shared node value
NDefines.NAI.PEACE_TERMS_TRADE_POWER_NO_TRADE_INTEREST_MULT = 0.5
NDefines.NAI.PEACE_TERMS_HUMILIATE_VALUE_MAX = 1.75 -- Max AI desire for humiliating its' enemy
NDefines.NAI.PEACE_TERMS_REVOKE_CORE_VASSAL_MULT = 0.6 -- AI desire for revoking cores is multiplied by this if the cores are on their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_REVOKE_CORE_FEAR_MULT = 1.75 -- AI desire for revoking cores is multiplied by this if they are afraid of the other country
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 5.0 -- AI desire for returning core provinces is multiplied by this for their vassals
NDefines.NAI.PEACE_TERMS_RETURN_CORES_NOT_FRIEND_MULT = 0.1 -- AI desire for returning core provinces is multiplied by this if they are not friends of the country core is being returned to
NDefines.NAI.PEACE_TERMS_RETURN_CORES_IMPERIAL_LIBERATION_MULT = 2.5 --AI desire for returning core province is multiplied by this if it's a target of Imperial Liberation CB war.
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_NO_INTEREST_MULT = 0.1 -- AI desire for annuling a treaty is multiplied by this if they have no strategic interests in doing so
NDefines.NAI.PEACE_TERMS_PROVINCE_HRE_UNJUSTIFIED_MULT = 0.1
NDefines.NAI.PEACE_TERMS_PROVINCE_STRATEGY_THRESHOLD = 0.125 -- If province has at least this strategic priority, AI values it higher in peace deals
NDefines.NAI.PEACE_TERMS_RETURN_PROVINCE_STRATEGY_MULT = 0.35
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SIZE_MULT = 0.125 -- AI desire mult for releasing vassal increased by this for each province they hold
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_MAX_MULT = 1.5 -- Max AI desire mult for releasing vassals
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_HRE_MULT = 2.25
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 0.2 -- AI desire for war reparations through peace
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_MIN_INCOME_RATIO = 0.9 -- AI only wants war reparations if other country has at least this % of their income
NDefines.NAI.DIPLOMATIC_ACTION_ALLIANCE_ACCEPTANCE_MULT = 2.25
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_BEFRIEND_FACTOR = 190 -- AI scoring for improve relations is increased by this if they have an attitude with 'befriend' desire
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_ALLY_FACTOR = 190
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_VASSALIZE_FACTOR = 200
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_EXISTING_RELATION_MULT = 20.0 -- AI scoring for military access is multiplied by this if it has an existing power cost relation
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_ENEMY_REGIMENTS_FACTOR = 2.5 -- AI scoring for military access is increased by this for each enemy regiment they are sheltering
NDefines.NAI.DIPLOMATIC_ACTION_VASSALIZE_DEVELOPMENT_FACTOR = 100
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_DEVELOPMENT_FACTOR = 10
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 1000 -- AI scoring for fabricating claims is always increased by this as long as the province is a conquest priority
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 2.0 -- AI scoring for fabricating claims based on strategic conquest priorities
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 1.5
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_FACTOR = 0.0
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 12.5
NDefines.NAI.DRILLING_BUDGET_OF_SURPLUS = 0.01
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 101
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.125					-- AI will only assign armies larger that this to a region
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 70				-- Max. amount of armies to use in new region assignment algorithm (fall back to old one)
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 80
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 1000					-- Influence on assimilation interest from number of provinces left to conquer
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 12
NDefines.NAI.WAR_MIN_WARSCORE_TO_JOIN = -5								-- Starting warscore for the AI to join a call for arms
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT = 0.45							-- Army <-> province distance impact on province evaluation
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 13.0							-- Border <-> province distance impact on province evaluation
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.025							-- AI will try to defend provinces under threat worth more than this percentage of total development
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 20
NDefines.NAI.BUY_INDULGENCE_BASE_AI_DESIRE = -1
NDefines.NAI.BUY_INDULGENCE_RIVAL_AI_DESIRE = -1						-- AI desire for buy indulgence if curia controller rivaled it, multiplied by budget/cost
NDefines.NAI.BUY_INDULGENCE_EXCOM_AI_DESIRE = -1
NDefines.NAI.APPOINT_CARDINAL_IN_OWNED_LAND_AI_DESIRE = 0.01
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = -1						-- AI scoring for becoming defender of faith, multiplied by budget/cost
NDefines.NAI.CALL_ECUMENICAL_COUNCIL_BASE_AI_DESIRE = -1				-- AI scoring for calling ecumenical council, multiplied by budget/cost
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 1	
NDefines.NAI.APPOINT_CARDINAL_WANTS_BEFRIEND = 200						-- AI scoring for appoint cardinals is increased by this if they have an attitude with 'befriend' desire
NDefines.NAI.APPOINT_CARDINAL_WANTS_ALLY = 200							-- AI scoring for appoint cardinals is increased by this if they have an attitude with 'ally' desire
NDefines.NAI.APPOINT_CARDINAL_CAN_INTEGRATE = 150
NDefines.NAI.ESTATE_PRIVILEGE_GRANT_THRESHOLD = 0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 0
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4

NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.1							-- Amount in percent to increase/decrease spending on budget posts when adjusting due to surplus/deficit
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 0.5					-- Above what rebel threat should the AI militarize (i.e. focus spending on armies)
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 1.5
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 1
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.5
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.5
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 0.3
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 0.3
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = -1




NDefines.NReligion.CONVERSION_ZEAL_DURATION = 1825
NDefines.NReligion.PIETY_MANPOWER = 0.5
NDefines.NReligion.MIN_CARDINALS = 15										-- Least amount of cardinals/ Starting cardinals
NDefines.NReligion.MAX_CARDINALS = 100
NDefines.NReligion.MAX_CARDINALS_PER_COUNTRY = 20
NDefines.NReligion.YEARLY_POPE_INVESTED_INFLUENCE_PER_CARDINAL = 0
NDefines.NReligion.MAX_PAPAL_INFLUENCE = 999								-- The maximum stored amount of papal influence for each country.
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.005
NDefines.NReligion.INVEST_PAPAL_INFLUENCE = 20.0
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 100
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_TREASURY_CONTRIBUTION = 1
NDefines.NReligion.BUY_INDULGENCE_COST_EXCOMMUNICATE_MULTIPLIER = 1
NDefines.NReligion.BUY_INDULGENCE_TREASURY_CONTRIBUTION = 1
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE = 0					-- Invested Influence given by appointing a cardinal
NDefines.NReligion.APPOINT_CARDINAL_CORRUPTION = 0.1						-- Corruption gained by the Papal State when appointing cardinals in its own land
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE_PAPAL_STATE = 0

NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 20
NDefines.NGovernment.FEUDAL_THEOCRACY_INTERACTION_COOLDOWN_YEARS = 10
NDefines.NGovernment.YEARLY_TRIBAL_ALLEGIANCE_MAX = 0
NDefines.NGovernment.TRIBAL_FEDERATION_ABILITY_COST = 50
NDefines.NGovernment.TRIBAL_ALLEGIANCE_HUMILIATE = 60.0
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 25.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 20.0
NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 2.5
NDefines.NGovernment.EXPAND_ADMIN_COST = 400.0
NDefines.NGovernment.LEADER_AS_MONARCH_TRADITION = 100
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0.5
NDefines.NGovernment.EXPAND_INFRASTRUCTURE_ADM_COST = 25
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -1
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.1

NDefines.NGui.AUTO_SELECT_EVENT_MONTHS = 6

NDefines.NEngine.EVENT_PROCESS_OFFSET = 30
