NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = 0				-- Prestige transferred for the Request to Share Maps diplomatic action.
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0
NDefines.NDiplomacy.MAX_PEACE_TREATY_COST = 100
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 15
NDefines.NDiplomacy.ANNUL_TREATIES_YEARS = 20
NDefines.NDiplomacy.COALITION_YEARS = 1
NDefines.NDiplomacy.MAX_ASKED_TRADE_POWER = 100
NDefines.NDiplomacy.COUNTERESPIONAGE_DISCOVER_CHANCE = 0.50
NDefines.NDiplomacy.SPY_NETWORK_SIEGE_EFFECT = 0.10
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.33
NDefines.NDiplomacy.PEACE_COST_DEMAND_NON_OCCUPIED_PROVINCE_MULT = 1
NDefines.NDiplomacy.DEFENDER_AE_MULT = 0.5
NDefines.NDiplomacy.STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 5
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 5
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 5
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 6
NDefines.NDiplomacy.MINIMUM_TRADE_POWER_TO_PREVENT_PRIVATEER = 0.1
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
NDefines.NDiplomacy.MIN_MONTHLY_COST_FOR_INFLUENCE_NATION = 2.084
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 5
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 10
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.FABRICATE_CLAIM_COST_MODIFIER_PER_CLAIM = 0.25
NDefines.NDiplomacy.CLAIM_STATE_MODIFIER = 0.25
NDefines.NDiplomacy.PEACE_COST_GOLD_STEP = 4
NDefines.NDiplomacy.PEACE_COST_WAR_REPARATIONS = 5
NDefines.NDiplomacy.PEACE_COST_HUMILIATE_RIVAL = 30
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.01
NDefines.NDiplomacy.FORCE_BREAK_ALLIANCE_TRUCE_YEARS = 0
NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0						-- Tributary State: Part of yearly income given in tribute
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.12						-- Tributary State: Part Adm tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.12						-- Tributary State: Part Dip tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.12						-- Tributary State: Base Mil tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.375					-- Tributary State: Part of yearly manpower given in tribute
NDefines.NDiplomacy.TRIBUTE_SENT_TRUST = 5						-- Tributary State: Bilateral Trust if tribute sent
NDefines.NDiplomacy.TRIBUTE_REFUSED_TRUST = 0
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 6	
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 2
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.48
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.12
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -20.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.5
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.36
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 30
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = 0
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.NEW_HEIR_LEGITIMACY_HIT = 0
NDefines.NCountry.NEW_HEIR_LEGITIMACY_THRESHOLD = 0		-- per dev
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.002	-- distance
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 1			-- Required prestige to to upgrade to government rank 2
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 25
NDefines.NCountry.PARLIAMENT_BACKING_PERCENTAGE = 40			-- average percent of seats backing an issue (0-100)
NDefines.NCountry.NUM_PARLIAMENT_ISSUES = 10
NDefines.NCountry.PARLIAMENT_PRESTIGE_HIT = 0				-- penalty if failed debate.
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 0.125
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = 0
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 10
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 5
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 0
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 5
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 5
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NCountry.PS_MOVE_CAPITAL_EXTRA = 20
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE = 0
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE_CAP = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_ATTACK_NATIVES = 1
NDefines.NCountry.PS_HARSH_TREATMENT_COST = 50
NDefines.NCountry.PS_IMPROVE_PROVINCE_CAPITAL_DISCOUNT = 0.005
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 0
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 20
NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 30.0
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.CORE_HAD_PERMANENT_CLAIM = 0.15
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.REGULAR_COLONY_GROWTH = 60
NDefines.NCountry.COLONIAL_CLAIM_BONUS = 20
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = 0
NDefines.NCountry.COLONY_VIOLAION_PAPAL_INFLUENCE_COST  = 0
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7.5	
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0.1
NDefines.NCountry.LIBERTY_DESIRE_HISTORICAL_RIVAL = 0
NDefines.NCountry.NORMAL_ELECTION_CYCLE = 5
NDefines.NCountry.SEIZE_TERRITORY_LIBERTY_MULTIPLIER = 3
NDefines.NCountry.HORDE_UNITY_PER_LOOT = 0.5
NDefines.NCountry.PROMOTE_INVESTMENTS_TRADEPOWER = 0
NDefines.NCountry.PROMOTE_INVESTMENTS_INFLATION = 0
NDefines.NCountry.INNOVATIVENESS_AHEAD_OF_TIME_BONUS = 0.005
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 4.0  -- Innovativeness bonus to first country (or countries) to reach a certain tech level.
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 2.0			-- Innovativeness bonus to first country (or countries) to pick an idea.
NDefines.NCountry.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 0														
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 7							
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.75				-- Multiplier on cost for advisors scripted with discount=yes
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 4
NDefines.NCountry.PS_RAISE_TARIFFS = 25
NDefines.NCountry.PS_LOWER_TARIFFS = 10
NDefines.NCountry.BASE_TARIFF = 0.15								-- Basic part of colonies income that goes to tariffs
NDefines.NCountry.TARIFF_INCREASE_STEP = 0.1					-- Increase on each boost
NDefines.NCountry.TARIFF_LIBERTY_INCREASE = 0.5					-- Liberty increase for each % tariffs
NDefines.NCountry.TARIFF_DECREASE_STEP = -0.1
NDefines.NCountry.MINIMUM_POLICY_TIME = 1
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0.0
NDefines.NEconomy.GOLD_MINE_SIZE = 20
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 1
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 10
NDefines.NEconomy.TRADE_POWER_HOME_BONUS = 0.15
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 40
NDefines.NEconomy.DECREASE_AUTONOMY_STEP = -10
NDefines.NEconomy.DECREASE_AUTONOMY_MIN = 0
NDefines.NEconomy.INCREASE_AUTONOMY_STEP = 10
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.04
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.04
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.1
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = -0.2
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 25
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 0.1
NDefines.NEconomy.LARGE_COLONIAL_NATION_LIMIT = 20
NDefines.NEconomy.PRIVATEER_INCOME_COLLECTION_EFF = 0.1
NDefines.NEconomy.CARAVAN_FACTOR = 10
NDefines.NEconomy.CARAVAN_POWER_MAX = 20
NDefines.NEconomy.CARAVAN_POWER_MIN = 1
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NMilitary.FORTRESS_COST = 0.16666666666
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 33.3
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 60
NDefines.NMilitary.CAWA_STARTING_STRENGTH = 0.1				-- Starting strength of a cawa regiment, 1.0 being full strength
NDefines.NMilitary.CAWA_STARTING_MORALE = 0.1
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 1
NDefines.NMilitary.GARRISON_SIZE = 3000 							-- GARRISON_SIZE
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER =  0.334			-- x times garrison to be able to siege.
NDefines.NMilitary.MAX_BREACH = 1
NDefines.NMilitary.TRANSPORT_SHIP_SAILORS_COST = 20					-- 1 = 1 men in cost.
NDefines.NMilitary.LIGHT_SHIP_SAILORS_COST = 50					-- 1 = 1 men in cost.
NDefines.NMilitary.GALLEY_SHIP_SAILORS_COST = 50
NDefines.NMilitary.GALLEY_TIME = 90							-- _MDEF_GALLEY_TIME = 10,
NDefines.NMilitary.TRANSPORT_TIME = 30				-- 1 = 1 men in cost.
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2							-- _MDEF_LIGHT_SHIP_COST = 10,
NDefines.NMilitary.GALLEY_COST = 10 								-- _MDEF_GALLEY_COST = 10,
NDefines.NMilitary.TRANSPORT_COST = 1
NDefines.NMilitary.LOOTED_SCALE = 2
NDefines.NMilitary.LOOTED_MAX = 10
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 8.0
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = 0
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.67
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50
NDefines.NMilitary.WAR_ENTHUSIASM_HIGH_THRESHOLD = -15
NDefines.NMilitary.PRESTIGE_TO_TRIBAL_ALLEGIANCE_FACTOR = 2
NDefines.NMilitary.LEADER_GAIN_PERSONALITY_BASE_CHANCE = 35.0
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 0
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 3
NDefines.NMilitary.CREATE_CAWA_MIL_COST = 0
NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 1.5			-- Rajput base cost is double as expensive
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 1.5
NDefines.NMilitary.MAX_DRILL_DECAY = 0.75
NDefines.NMilitary.JANISSARIES_USES_CONSTRUCTION = 1
NDefines.NMilitary.FLAGSHIP_REQUIRED_NAVY_SIZE_IN_SAILORS = 750
NDefines.NMilitary.MERCENARY_COMPANY_STARTING_MORALE = 0.25
NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 10
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 10
NDefines.NMilitary.MERCENARY_REINFORCE_COST_MULTIPLIER = 0.25
NDefines.NMilitary.SIEGE_BONUS_FOOD_SHORTAGE = 1
NDefines.NMilitary.SIEGE_BONUS_WATER_SHORTAGE = 1
NDefines.NMilitary.SIEGE_BONUS_DEFENDERS_DESERT = 1
NDefines.NMilitary.NAVAL_DOCTRINE_SAILORS_COST = 0.05			-- Cost for switching naval doctrine (Share of sailors)
NDefines.NMilitary.NAVAL_DOCTRINE_MIN_FORCE_LIMIT = 15
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0	-- Multiplier for morale damage taken by backrow
NDefines.NMilitary.BACK_LINE_STRENGTH_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.BACK_LINE_REINFORCE_SPEED = 40
NDefines.NMilitary.CAVALRY_BREAKTHROUGH = 0.5
NDefines.NMilitary.INFANTRY_BREAKTHROUGH = 0.05
NDefines.NMilitary.CAROLEAN_BASE_COST_MODIFIER = 2.0
NDefines.NMilitary.CAROLEAN_USES_CONSTRUCTION = 1
NDefines.NMilitary.CAROLEAN_STARTING_STRENGTH = 1.0
NDefines.NMilitary.CAROLEAN_STARTING_MORALE = 0.1
NDefines.NMilitary.CREATE_HUSSARS_MIL_COST = 0				-- Cost to create Hussars (per unit)
NDefines.NMilitary.HUSSARS_USES_CONSTRUCTION = 1
NDefines.NMilitary.HUSSARS_BASE_COST_MODIFIER = 2.0
NDefines.NMilitary.HUSSARS_STARTING_STRENGTH = 1.0
NDefines.NMilitary.HUSSARS_STARTING_MORALE = 0.1
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.1 -- Starting strength of a banner regiment, 1.0 being full strength
NDefines.NMilitary.REGULAR_LEADER_POWER = 0.70
NDefines.NMilitary.EXPLORER_LEADER_POWER = 0.60
NDefines.NMilitary.LEADER_MAX_PIPS = 8							-- Max general/admiral pips (per skill)
NDefines.NMilitary.LEADER_MIN_PIPS = 2
NDefines.NMilitary.INSUFFICIENT_SUPPORT = -0.5
NDefines.NAI.BIGSHIP_FRACTION = 0.1
NDefines.NAI.TRANSPORT_FRACTION = -1 -- Max fraction of naval forcelimit that should be transports
NDefines.NAI.PEACE_TIME_MONTHS = 12
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0
NDefines.NAI.PEACE_WARGOAL_FACTOR = 0.5 -- AI unwillingness to peace based on holding the wargoal
NDefines.NAI.PEACE_CAPITAL_FACTOR = 20
NDefines.NAI.PEACE_ALLY_WARSCORE_MULT = 1
NDefines.NAI.PEACE_ALLY_WARGOAL_MULT = 2 -- Multiplies PEACE_WARGOAL_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_CAPITAL_MULT = 1
NDefines.NAI.PEACE_DESPERATION_FACTOR = 20
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 0
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 1825
NDefines.NReligion.YEARLY_POPE_INVESTED_INFLUENCE_PER_CARDINAL = 0
NDefines.NReligion.MAX_PAPAL_INFLUENCE = 999								-- The maximum stored amount of papal influence for each country.
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 100
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_TREASURY_CONTRIBUTION = 1
NDefines.NReligion.BUY_INDULGENCE_COST_EXCOMMUNICATE_MULTIPLIER = 1
NDefines.NReligion.BUY_INDULGENCE_TREASURY_CONTRIBUTION = 1
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE = 0					-- Invested Influence given by appointing a cardinal
NDefines.NReligion.APPOINT_CARDINAL_CORRUPTION = 0.1						-- Corruption gained by the Papal State when appointing cardinals in its own land
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE_PAPAL_STATE = 0
NDefines.NReligion.PIETY_MANPOWER = 0.5
NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 20
NDefines.NGovernment.FEUDAL_THEOCRACY_INTERACTION_COOLDOWN_YEARS = 10
NDefines.NGovernment.TRAIN_HORSEMANSHIP_DURATION_YEARS = 10
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_AMOUNT = 10
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_TIME = 0.25
NDefines.NGovernment.TRIBAL_ALLEGIANCE_MAX = 100
NDefines.NGovernment.YEARLY_TRIBAL_ALLEGIANCE_MAX = 0.0
NDefines.NGovernment.TRIBAL_ALLEGIANCE_HUMILIATE = 30.0 -- TA gained from doing Humiliate or Show Strength in a war.
NDefines.NGovernment.TRIBAL_FEDERATION_ABILITY_COST = 50
NDefines.NGovernment.ENLIST_GENERAL_TRADITION = 30
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 25.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 25.0
NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 2.5
NDefines.NGovernment.CENTRALIZE_STATE_ADM_COST = 25
NDefines.NGovernment.EXPAND_ADMIN_COST = 400.0
NDefines.NGovernment.LEADER_AS_MONARCH_TRADITION = 15
NDefines.NGui.AUTO_SELECT_EVENT_MONTHS = 6
NDefines.NGovernment.EXPAND_INFRASTRUCTURE_ADM_COST = 0
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 0
NDefines.NCountry.POWER_MAX = 9999 -- Default 999